### ISSUE TITLE
s11s"Vertical" and "Horizontal" confused in footprint names

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Potentiometers.pretty#18]
@jkriege2 
When looking at the footprints in your PR at https://github.com/KiCad/Potentiometers.pretty/pull/16, I believe for many of these footprints the naming is incorrect; "Vertical" and "Horizontal" are switched!

I've marked "H" or "V" on some of the footprints where they're wrong:
![image](https://user-images.githubusercontent.com/1936989/28387562-70b2f5da-6c84-11e7-824a-68afce1bbc71.png)

You can make a distinction on the trimmer as to whether the position refers to the mounting or the adjustment. But since the pots with shafts, like ALPS RK09, are very clear and use the shaft orientation (vertical means the shaft sticks up away from the PCB while horizontal has the shaft parallel to the PCB) it makes sense to me that we stick with that. So for trimmers if the adjustment tool points at the PCB it's vertical and if the adjustment tool lays parallel with the PCB it's horizontal.

Can you please check this out and, if I'm right, update the script and footprints (if possible)?

**Comment by jkriege2** [comment]
I can have a look (but might take some time ... as I'm quite busy at the moment) ... I chose this naming, as it is the way these parts are familiar to me ... usually they are sold as "liegend" (lying) and "stehend" (standing) in germany ... and I tried to make that clear in the wording ... I think the rationale could be that for the trimmers there is no obvious shaft (usually), so the body is what we look at. For the pots the shaft is prominent, so that counts more (to me), especially as these are often associated with the frontplate ...

But that's just my interpretation and we can do it any way that makes sense to most ...

@SchrodingersGat @pointhi @CarlPoirier @diggit @easyw any input on this?

JAN

**Comment by easyw** [comment]
typically the manufacturers say: 
Horizontal mount, Vertical mount
http://www.nobleusa.com/rpotbm.html

**Comment by evanshultz** [comment]
Yes, as I stated. Noble calls them "horizontal" when the shaft is parallel to the PCB. Same for ALPS and every other pot with a shaft I've seen.

As I mentioned, trimmers could possibly spawn a discussion but on pots with a shaft it should be a simple (I suppose) update to the script.

**Comment by diggit** [comment]
IMO most universal rule would be rotation axis direction.
Perpendicular to PCB -> Vertical
Parallel with PCB -> Horizontal

**Comment by SchrodingersGat** [comment]
It should be the alignment of the shaft (relative to the PCB) that determines the Horizontal / Vertical naming convention. I agree that these parts need changing.

**Comment by evanshultz** [comment]
I'm addressing this issue.

**Comment by jkriege2** [comment]
Will you fix it in the script https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Potentiometers?

**Comment by evanshultz** [comment]
@jkriege2 Yes, of course!

**Comment by evanshultz** [comment]
@jkriege2 I'm almost done with the updated pot footprints and I hope you can you answer a questions about these footprints for me since this was your original script?
1. Bourns PRS11S doesn't have an annular ring. Is that on purpose?
1. Why do ACP CA14VSMD (and similar) have specific bottom-mounted footprints? Why not have hole and non-hole versions that could be mirrored to the bottom side if desired?
1. Why are the 3D models scaled to 1/2.54?

**Comment by jkriege2** [comment]
Hi!

1. The DS doesn't show any ... but maybe it makes sense to have them, so you can form a more solid bond between the housing and the PCB ...
![2017-11-21 20_03_56-prs11s pdf - adobe acrobat reader dc](https://user-images.githubusercontent.com/11967523/33091389-44fdba26-cef7-11e7-87f5-3d82357a4a51.png)
2. That's with a hole in the center (so you can have it mounted from bottom, but with an axis going through the PCB, or on top or bottom and an axis pointing away from the PCB:
![2017-11-21 20_07_22-3d viewer](https://user-images.githubusercontent.com/11967523/33091549-b6f7538a-cef7-11e7-9883-cdd8c16daf28.png)
![2017-11-21 20_07_15-3d viewer](https://user-images.githubusercontent.com/11967523/33091550-b71ef2b4-cef7-11e7-9f08-5f67cf8063dc.png)
![2017-11-21 20_07_00-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb](https://user-images.githubusercontent.com/11967523/33091551-b73d88f0-cef7-11e7-8874-213eaed4068b.png)
3. Because I semi-scripted them (you need parametrizeable FcStds + the scripts that are generated by my footprint script), but since I don't know how to export properly by Python directly from FreeCAD, I had to do the standard export, which leads to the 1/2.54-scaling. ... and I didn't have time to reexport everything by hand properly yet.

Best,
JAN

**Comment by evanshultz** [comment]
1. Yeah... I wasn't sure if that was left up to the user or if it was intended to be an unplated hole. I'll leave it like it is.
2. So the only difference is the shaft position? Since one can flip the component to the back side of the PCB, only the 3D model with the shaft on the bottom of the part is different. Right? To me, that seems little reason to have the `MountLS` versions. When I saw this nomenclature, I expected to see a pot that is only able to be mounted on the back of the PCB, like this (Noble V16L4):
![image](https://user-images.githubusercontent.com/1936989/33140807-ea6ee4d0-cf65-11e7-8eb9-f480719d6638.png)
Would that be a better use of this kind of term?
3. OK. v5 should have all normal 3D parameters.

**Comment by jkriege2** [comment]
It also covers Pots as you mention 
![2017-11-22 20_28_55-library browser potentiometers c__development_kicad_share_kicad_modules_pote](https://user-images.githubusercontent.com/11967523/33146284-d4893784-cfc3-11e7-9431-cb000156d83a.png)
I think the main difference is having the hole for the axis, or not having it. I would like to see these variants, as otherwise you will have to add a hole somewhere and hope it's right ... this way the hole is positioned correctly for a specific pot, which should be mounted that way.

**Comment by evanshultz** [comment]
@jkriege2 Right! Thanks for clarifying your intentions. The picture I sent is for a pot that is only back-mounted. For others, there could be a version with a hole and a version without a hole. The user could flip the one with a hole to the back side after placement on the board to achieve the same effect. To me, that is less confusing and better because the only footprints for back-mounted are ones where there are specific pots meant to be used in that configuration. So having back mounting and a hole are unique options that can be used as needed, but they aren't forced to go together. Any concerns with that? Am I missing anything?

**Comment by jkriege2** [comment]
But then I don't understand what the use of a hole is if the pot is not using it (i.e. mounted on the back), or do you propose to make the footprint having the pot on the front always and having a version with the axis pointing away from the fron-side (no hole) and one going through the front (with a hole). I.e. we have a version with and one without the hole, but the component of always on the front ...

A feature of the MountLS-version is that there is dashed silkscreen drawing on the front to indicate that the component is back-mounted+ silkscreen on the back ... should we keep that?

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 Correct.

If the vertical pot is intended to mount on the back, then there is a footprint for that. Like the image I posted above or http://www.omeg.co.uk/lt6stbrc.htm. I don't think silk on the front is necessary as there are no parts on the front and it may be no problem to place parts or put copper there. We don't put silk on the bottom for front-mounted parts.

For any other vertical pot that can have a shaft going up or down (so like the Piher PT-6v you posted above but not like [this](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIJ62lx3wgbvhvXbs40okg8JJW85TxnUMxLJ9xUG60X_qNwKRIzQ)), there is a version without a hole. And there can be a separate footprint with a hole to allow the shaft-down version of the part. In any case, the pots will always sit on the top of the board (the user can flip them if they wish).

BTW, have you ever seen a trimmer/pot with the downward pointing shaft? If the PCB was right next to a metal panel and the trimmer couldn't fit on the top side, that would allow a shaft sticking through the panel for the user to adjust. But otherwise I struggle to think of where this might be used. And I've not seen one, so maybe I'm just not creative enough to think of the possibilities.

Anyway, does that make sense? Can you see any problems or gotchas?

**Comment by jkriege2** [comment]
About the trimmers ... that was about the intended use-case ... Also look at this DS from Piher: http://www.piher-nacesa.com/pdf/14-PT15v03.pdf on p. 3 ... They propose holes (even with size and all) for each vertical pot.

Best,
JAN

**Comment by jkriege2** [comment]
PS: I don't see any problems with your plan ... will you do the scripting?
BTW: Do you rewrite or "just" update my scripts?

**Comment by evanshultz** [comment]
@jkriege2 Thanks for the link!I've been updating your scripts and not touching the code except where needed. I think a through re-write would be nice, but adding the argument parsing and other major bits will allow the core functions to be re-written later (after v5).

**Comment by evanshultz** [comment]
Fixed by https://github.com/KiCad/kicad-footprints/pull/190.
